openapi: '3.0.0'
info:
  version: 1.0.0
  title: Yocheved Zelishovsky
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /properties:
    get:
      summary: List all properties
      operationId: listProperties
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of properties
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create property
      operationId: createProperty
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /properties/{propertyId}:
    get:
      summary: Get property info
      operationId: showPropertyById
      parameters:
        - name: propertyId
          in: path
          required: true
          description: The id of the property to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Properties'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /posts:
    get:
      summary: List social posts
      operationId: listPosts
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of social posts
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Posts'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create social post
      operationId: createPost
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Property:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
    Properties:
      type: array
      items:
        $ref: '#/components/schemas/Property'
    Post:
      required:
        - id
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        scheduledAt:
          type: string
    Posts:
      type: array
      items:
        $ref: '#/components/schemas/Post'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string